name: build-and-publish
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    #- name: npm install, build and test
    #  run: |
    #    ls -la
    #    npm install
    #    npm run build
    
    - name: e1
      run: eval "$(ssh-agent -s)"
      
    - uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }} 
      with:
        source-directory: './' #//TODO: Визначити правильно директорію
        destination-github-username: 'BogdanDraguzia'
        destination-repository-name: 'BogdanDraguzia.github.io'
        user-email: draguziabogdan@gmail.com
        target-branch: master
        target-directory: './'
